version: '3.11'
services:
  web:
    build: .
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - gxxg_test_network
  
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/gxxg/

volumes:
  postgres_data: 

networks:
  gxxg_test_network: