version: '3.11'
services:  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: ["sh", "-c", "python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py collectstatic --no-input; gunicorn GxxG.wsgi:application --bind 0.0.0.0:8000"]
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/sites-enabled/default.conf
      - nginx_logs:/var/log/nginx  # Volume for Nginx logs

    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
  nginx_logs:  # Define the volume for Nginx logs
